### ISSUE TITLE
Error when calling commentions('list') in template

### ISSUE THREAD

**Issue by hariom147** [sebastiangreger/kirby3-commentions#142]
Hi @sebastiangreger, 

first of all thank you for this plugin. Only after doing some research can I see how much thought and effort you put into this.

I installed a clean starterkit and the v2.0-beta.4 of your plugin (following the instrucions in this repo) and get the following error when visiting the a page of a template which has `<?php commentions('list') ?>` in it.

>Declaration of sgkirby\Commentions\Structure::__set(string $id, $props) must be compatible with Kirby\Cms\Structure::__set(string $id, $props): void
>
>Stacktrace:
/starterkit/site/plugins/commentions/lib/Structure.php:35

**Comment by sebastiangreger** [comment]
Hi thank you for identifying this issue, caused by a change introduced with the most recent 3.7.1 version of Kirby core ([ref](https://github.com/getkirby/kirby/commit/f434c851ff748cdefb8342e6076152851005dd11)).

I just pushed a commit to the `develop` branch that should fix it for the v2 beta?

**Comment by hariom147** [comment]
Needed to manually fix [this line](https://github.com/sebastiangreger/kirby3-commentions/commit/042487607aa2204c153384aa22519f1705bd0406), too. and now it's working again. Thank you.

**Comment by macx** [comment]
🤔 Still not working after fixing it manually in `Commention.php#126`. (Kirby 3.8.3)

**Comment by sebastiangreger** [comment]
Hi @macx. I have not been able to formally test the plugin beyond Kirby 3.7 and it is actually going to be retired/archived in the coming days (see note below). I am however still running it on a 3.8.2 site at this moment where it works without errors.

Could you specify what is not working? Are you getting this same `Declaration of sgkirby\Commentions\Structure::__set(string $id, $props) must be compatible with Kirby\Cms\Structure::__set(string $id, $props): void` error?

If you are using the latest code from the `develop` branch (NB. not the last "released" beta version `2.0-beta.4`, as the fix referred to in this thread was never released as a new version), the method call at `lib/Structure.php#35` should read `public function __set(string $id, $props): void` (that `void` is missing from the `2.0-beta.4` and led to the observed error with 3.7.x). I am unable to comment on whether or what change is needed in `Commention.php#126`; that version check referred to should be valid for any version from 3.6.0 onwards and deals with an unrelated change in core regarding translation functionalities.

I am sorry for the inconvenience. The lack of resources to keep putting in this kind of effort to maintain the plugin up-to-date is the exact reason why I unfortunately have to give up its development – this is explained in more detail over at: [#151 Sunsetting the Commentions plugin](https://github.com/sebastiangreger/kirby3-commentions/issues/151).

**Comment by macx** [comment]
@sebastiangreger Sad, that you end develop this plugin.

But thanks for the hint: With telling composer to pull the develop branch, it's working. Kind of. I don't get the user form displayed, just the Webmention. Any hint?

`<?php commentions('form') ?>`

**Comment by sebastiangreger** [comment]
> I don't get the user form displayed, just the Webmention. Any hint?

Are comments enabled in config for the template in question? https://github.com/sebastiangreger/kirby3-commentions/tree/develop#activate-by-template

**Comment by macx** [comment]
Sorry for the late answer @sebastiangreger. My fault, they were not enabled.
