### ISSUE TITLE
Change return values from array to object?

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#16]
@sebastiangreger What also came into my mind: The plugin currently uses lots of arrays in the snippets (see e.g. `snippets/commentions-list.php`). What do you think about rewriting this to follow a more Kirby-/jQuery-like syntax? Instead of writing things like `htmlspecialchars($comment['name'])`, this would allow using a more familiar syntax like `$comment->name()->html()` instead. It’s basically not that complicated and would allow us to more of the logic into the backend, to clean up the snippets code.

Instead of writing …
```
<?= $name = (
        (isset($comment['name']) && $comment['name'] != null)
            ? htmlspecialchars($comment['name'])
            : t('commentions.snippet.list.anonymous')
) ?>
```

… we would just need …

```
<?= $comment->name()->html() ?>
```

… in the template, because the `name()` method of a comment could handle all the logic itself. The same could also easily be applied to URL formatting etc. What do you think?

_Originally posted by @fabianmichael in https://github.com/sebastiangreger/kirby3-commentions/issues/13#issuecomment-616140250_

**Comment by sebastiangreger** [comment]
@fabianmichael Anything that makes it "more Kirby" is most welcome. Sounds like a great simplification. So, this would mean that at least page method $page->commentions() (maybe others for consistency?) would return an object instead of an array? Is this something we can "glue on" (e.g. by adding a class that handles these methods and translates the output of the current code into an object) or does it require deeper changes across the entire plugin?

**Comment by fabianmichael** [comment]
Hi @sebastiangreger,

I could not resist to stark working on this today. It was a bit of exploration into finding the simplest solution, sorry that I squashed all of it into a single big commit (see #24)!

I ended with extending Kirby’s built-in `Structure` object, which required very little code to get it right. We got a local `Structure` class now and a `Commention` class, which extends Kirby’s `StructureObject`. As the new `Commentions::get()` (see below) now returns a Structure object, this one can easily be converted to an array by calling the `toArray()` method, if one wants to work with the raw commentions data (e.g. panel section or migration assistant).

It works great so far, I did some other thing that we might want to talk about (please be honest, if you don’t like anything :-) ):

- I changed indentation width in `.editorconfig` from 4 => 2 spaces for snippet files, as this is what most Kirby code uses.
- I changed the method name of `Commentions::retrieve()` => `Commentions::get()`, as I though this one might be easier to type. No hard feelings, if you want to revert this. I also removed the sort parameter, as sorting can now easily be handled by calling one of the respective native `Collection` methods (e.g. `$commentions->flip()` or `$commentions->sortBy('timestamp', 'asc')`)
- I changed the way of how translation strings are composed. You composed strings like `mentioned` + ` at`, which could turn out to be problematic with languages, that have a very different grammer from German or English, so I made 2 separate strings for dealing with that.
- Kirby provides the option of changing the default date handler. As `date()` does not translation day/month names, I find myself very often to switche the date handler to `strftime()`, which supports localization. The plugin now respects the date handler setting of Kirby.
- Empty groups are now skipped when reactions are grouped. I can also revert that, if you want me to.

I’m happy to hear your feedback! :-)

⚠️ Please **do not merge** my pull request with `dev` yet, as the readme has not been updated. ⚠️

**Comment by sebastiangreger** [comment]
Hi, and :exploding_head:! ...in a good way

I read the code once and like it very much - this is the "glue on" gentle rewrite I had been hoping for; happy to see it fitting so well into the existing code base. I am still looking into some of the details (that's a pretty heavy PR, sir! :rofl:), but a quick observation from testing with the local version of my website - might be easier for you to look into than me trying to wrap my head around it:

https://github.com/sebastiangreger/kirby3-commentions/blob/6a2dd865bf86378cc0c71e7e6dc31abe303e3e7b/classes/Frontend.php#L72

...throws an error "Call to a member function count() on array". This is because $groups is the array with the grouping configuration, not an object with commentions?

On a related note, re:

https://github.com/sebastiangreger/kirby3-commentions/blob/6a2dd865bf86378cc0c71e7e6dc31abe303e3e7b/classes/Frontend.php#L68

A default "grouping setup" is already defined in the options array in `index.php`; I assume what you intend here is that, if no grouping array is set, that is the same as "no grouping please"?

**Comment by fabianmichael** [comment]
Uff! I’m glad that you like it, @sebastiangreger! :-)

> ...throws an error "Call to a member function count() on array". This is because $groups is the array with the grouping configuration, not an object with commentions?

Sorry, this was just a type, fixed in my latest commit.

> A default "grouping setup" is already defined in the options array in index.php; I assume what you intend here is that, if no grouping array is set, that is the same as "no grouping please"?

It was just not necessary, because the config value already has a default. Removed it, as it would have never been applied.

**Comment by fabianmichael** [comment]
Uff! I’m glad that you like it, @sebastiangreger! :-)

> ...throws an error "Call to a member function count() on array". This is because $groups is the array with the grouping configuration, not an object with commentions?

Sorry, this was just a type, fixed in my latest commit.

> A default "grouping setup" is already defined in the options array in index.php; I assume what you intend here is that, if no grouping array is set, that is the same as "no grouping please"?

It was just not necessary, because the config value already has a default. Removed it, as it would have never been applied.

**Comment by sebastiangreger** [comment]
@fabianmichael Thanks, eliminating that typo fixed the issue. But I still receive an error when rendering the `<?php commentions('grouped') ?>` helper if the YAML file contains likes etc.:

> Argument 1 passed to Kirby\Cms\Collection::__set() must be of the type string, null given, called in /home/sebu/Projects/websites/test2/kirby/src/Toolkit/Collection.php on line 834

To replicate the error, you can use this file as `commentions.yml` for a page:

```yaml
-
  name: Testy McTesting
  text: >
    A rather simple comment with just a line
    of text. User entered their name.
  timestamp: 2020-04-15 11:20
  type: comment
  status: approved
  uid: a50vylqwl5
-
  name: John Doe
  timestamp: 2020-04-15 11:50
  type: like
  status: approved
  source: https://example.com/some-post
  uid: 126los473p
```

...it contains no more than one comment and on like, but the grouped rendering causes above error.

**Comment by sebastiangreger** [comment]
Ooops, sorry that was not intended to look the way it does... I just removed duplicate comments; didn't know Github would present it like this, making it look like censorship or content moderation :upside_down_face:

**Comment by fabianmichael** [comment]
@sebastiangreger Fixed it! :-)

**Comment by sebastiangreger** [comment]
@fabianmichael Thanks - tested and confirmed! Now the error is gone.

**Comment by sebastiangreger** [comment]
So, I finally got back into a more thorough review of the changes from this move to a structure... Looks like this works really well (now that the few, always unavoidable, glitches are fixed) and tastes much more "Kirby" than the original draft. I have two or three questions, but nothing major:

* Just to make sure I got this right: the Commention object being based on Kirby's Structure object means a developer may use any of these https://getkirby.com/docs/reference/@/classes/cms/structure to process them further? Or is it only the ones you have listed in `Commention.php` (as a matter of fact, not everything that can be done with a Kirby structure seems to be useful for comments?)

* I'm not sure what `isAuthenticated()` does? Do you mean "approved"? Or is this something completely different?

* Does the function `name()` mean that it essentially overrides the shortcut `$comment->name()` that would by default return the string in the `name` field with that "processed" name? So, if a developer really would want to write their own presentation logic, they would get all the fields like `$comment->uid()`, `$comment->timestamp()` etc., but for the name field, it would be `$comment->content()->get('name')`?

How should we proceed from here, with the code base as well as with the next steps, @fabianmichael?

**Comment by fabianmichael** [comment]
>     * Just to make sure I got this right: the Commention object being based on Kirby's Structure object means a developer may use any of these https://getkirby.com/docs/reference/@/classes/cms/structure to process them further? Or is it only the ones you have listed in `Commention.php` (as a matter of fact, not everything that can be done with a Kirby structure seems to be useful for comments?)

I extended the native Kirby objects to add a few custom methods, that I did not want to define as global field/pages methods, e.g. `safeText()` and `dateFormatted()`. Also the commentions-plugin uses the `uid` key, whereas Kirby’s structure uses `id`. It would have worked by using the `Structure` and `StructureObject` casses directly, but by extending them, we can add commention-specific methods.

>     * I'm not sure what `isAuthenticated()` does? Do you mean "approved"? Or is this something completely different?

In the `commentions-list.php` snippet, there was a line mentioning a commention property called `authenticated`, I just took it over because I thought you got some plans with that. Can be removed, if not needed.

>     * Does the function `name()` mean that it essentially overrides the shortcut `$comment->name()` that would by default return the string in the `name` field with that "processed" name? So, if a developer really would want to write their own presentation logic, they would get all the fields like `$comment->uid()`, `$comment->timestamp()` etc., but for the name field, it would be `$comment->content()->get('name')`?

Yes, that’s correct.
> 
> 
> How should we proceed from here, with the code base as well as with the next steps, @fabianmichael?

**Comment by sebastiangreger** [comment]
> I extended the native Kirby objects [...] by extending them, we can add commention-specific methods.

:+1: 

> In the `commentions-list.php` snippet, there was a line mentioning a commention property called `authenticated`, I just took it over because I thought you got some plans with that. Can be removed, if not needed.

I believe the idea was at some point that there would be a means to "authenticate" comments. I.e. if you write a comment while logged in as admin, there would be a field "authenticated" (bool or a user ID), so in the frontend it could be presented as "comment by the site owner". This is obviously a roadmap feature, so we could leave it in as an undocumented stub to pick up later (as an "is..." function it should basically return boolean, no matter what the payload of a future "authenticated" field might be). Thanks for pointing out it was my own brain child :laughing: ...a leftover from an old thought I had long forgotten about.

> > ```
> > * Does the function `name()` mean that it essentially overrides the shortcut `$comment->name()` that would by default return the string in the `name` field with that "processed" name?
> > ```
> 
> Yes, that’s correct.

For consistency, would you be opposed to the idea that we either have a function `$commention->nameFormatted()` (or similar) and keep `->name()` to give direct access to the raw field? Alternatively, this logic of rendering empty names as "Anonymous" could also be moved to the snippet (or to `sourceFormatted()`?) entirely, as it is a rather opinionated implementation that I believe anybody writing their own list snippet might have different ideas about anyways. What do you think?

**Comment by fabianmichael** [comment]
> For consistency, would you be opposed to the idea that we either have a function $commention->nameFormatted() (or similar) and keep ->name() to give direct access to the raw field? Alternatively, this logic of rendering empty names as "Anonymous" could also be moved to the snippet (or to sourceFormatted()?) entirely, as it is a rather opinionated implementation that I believe anybody writing their own list snippet might have different ideas about anyways. What do you think?

Jep … see #36

**Comment by sebastiangreger** [comment]
This is mainly done - let's open separate issues for any bugs and fine tuning.
